"""
Generate Mel filterbank coefficients (40 filters x 129 FFT bins)
Output: Core/Inc/mel_bank.h
"""
import numpy as np

SAMPLE_RATE = 16000
FFT_N      = 256
NUM_MELS   = 40
F_MIN      = 20.0
F_MAX      = 8000.0

def hz_to_mel(hz):
    return 2595.0 * np.log10(1.0 + hz / 700.0)

def mel_to_hz(mel):
    return 700.0 * (10.0 ** (mel / 2595.0) - 1.0)

# FFT frequency bins
freqs = np.linspace(0, SAMPLE_RATE / 2, FFT_N // 2 + 1)  # 0..8000, 129 bins

# Mel points (uniform in mel space)
mel_points = np.linspace(hz_to_mel(F_MIN), hz_to_mel(F_MAX), NUM_MELS + 2)
hz_points  = mel_to_hz(mel_points)
bin_points = np.floor((FFT_N + 1) * hz_points / SAMPLE_RATE).astype(int)
# Force minimum spacing of 1 bin to avoid degenerate triangular filters
for i in range(1, len(bin_points)):
    if bin_points[i] <= bin_points[i - 1]:
        bin_points[i] = bin_points[i - 1] + 1
# Clip to valid range
bin_points = np.clip(bin_points, 0, FFT_N // 2)

# Build filterbank
mel_bank = np.zeros((NUM_MELS, FFT_N // 2 + 1))
for m in range(1, NUM_MELS + 1):
    left  = bin_points[m - 1]
    center = bin_points[m]
    right = bin_points[m + 1]
    for k in range(left, center):
        mel_bank[m - 1, k] = (k - left) / max(center - left, 1)
    for k in range(center, right):
        mel_bank[m - 1, k] = (right - k) / max(right - center, 1)

# Write C header
with open("../Core/Inc/mel_bank.h", "w") as f:
    f.write("// Auto-generated by scripts/gen_mel_bank.py — DO NOT EDIT\n")
    f.write(f"// {NUM_MELS} mel filters x {FFT_N//2+1} FFT bins @ {SAMPLE_RATE}Hz\n")
    f.write("#ifndef __MEL_BANK_H__\n")
    f.write("#define __MEL_BANK_H__\n\n")
    f.write(f"#define MEL_NUM_FILTERS {NUM_MELS}\n")
    f.write(f"#define MEL_FFT_BINS    {FFT_N // 2 + 1}\n\n")
    f.write(f"static const float mel_bank[MEL_NUM_FILTERS][MEL_FFT_BINS] = {{\n")
    for m in range(NUM_MELS):
        vals = ", ".join(f"{v:.8f}f" for v in mel_bank[m])
        f.write(f"    {{{vals}}},\n")
    f.write("};\n\n")
    f.write("#endif\n")

print(f"Generated: Core/Inc/mel_bank.h ({NUM_MELS}x{FFT_N//2+1})")

# Verify: each filter should have at least some non-zero values
empty = sum(1 for m in range(NUM_MELS) if np.all(mel_bank[m] == 0))
print(f"Empty filters: {empty}/{NUM_MELS}")
print(f"Filter sum range: {mel_bank.sum(axis=1).min():.4f} - {mel_bank.sum(axis=1).max():.4f}")
