; ESP8266-01S WiFi+MQTT Bridge for STM32H743 AI Hear
[env:esp01_1m]
platform = espressif8266
board = esp01_1m
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.flash_mode = dio
upload_resetmethod = ck
lib_deps =
    knolleary/PubSubClient @ ^2.8
    ESP8266WebServer
